extends Reference
class_name SteeringMotion2D
"""
A container that holds a linear and rotational amount of acceleration generated by steering behaviors.
"""

var linear_motion: = Vector2()
var rotational_motion: float = 0

"""
Sets the linear and rotational acceleration amounts to zero
"""
func zero() -> void:
	linear_motion.x = 0
	linear_motion.y = 0
	rotational_motion = 0


"""
Returns true if both the linear and rotational acceleration amounts are zero
"""
func is_zero() -> bool:
	return linear_is_zero() and rotational_is_zero()


"""
Returns true if the linear acceleration amount is zero
"""
func linear_is_zero() -> bool:
	return linear_motion.x == 0 and linear_motion.y == 0


"""
Returns true if the rotational acceleration amount is zero
"""
func rotational_is_zero() -> bool:
	return rotational_motion == 0