extends Reference
class_name SteeringMotion2D
"""
A container that holds a linear and angular amount of acceleration generated by steering behaviors.
"""

var motion: = Vector2.ZERO
var angular_motion: = 0.0


func reset_values() -> void:
	motion = Vector2.ZERO
	angular_motion = 0.0


func is_zero() -> bool:
	return motion == Vector2.ZERO and angular_motion == 0.0
